# Generated by Django 5.2.6 on 2025-11-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
