# Generated by Django 5.2.6 on 2025-11-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0003_alter_album_format_alter_album_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='album',
        ),
    ]
