# Generated by Django 5.2.6 on 2025-12-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0006_alter_dottifyuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
