# Generated by Django 5.2.6 on 2025-12-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0007_alter_album_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='length',
            new_name='running_time',
        ),
    ]
