# Generated by Django 5.2.6 on 2025-12-05 10:58

import django.core.validators
import django.utils.timezone
import dottify.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0009_rename_running_time_song_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[dottify.validators.valid_release_date]),
        ),
        migrations.AlterField(
            model_name='album',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999.99)]),
        ),
    ]
