# Generated by Django 5.2.6 on 2025-12-05 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0010_alter_album_release_date_alter_album_retail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
